#!/bin/sh

curl -4 -s -X PUT \
    -H "Authorization: Bearer ${APIKEY}" \
    -d '{"target":"[remote_addr]"}' \
    "https://api.linode.com/v4/domains/${DOMAINID}/records/${RECORDIDA}"
curl -6 -s -X PUT \
    -H "Authorization: Bearer ${APIKEY}" \
    -d '{"target":"[remote_addr]"}' \
    "https://api.linode.com/v4/domains/${DOMAINID}/records/${RECORDIDAAAA}"
