#!/bin/sh

wget -4 -qO- --no-check-certificate "https://api.linode.com/?api_key=${KEY}&api_action=domain.resource.update&domainid=${DOMAINID}&resourceid=${RESOURCEIDA}&target=[remote_addr]"
wget -6 -qO- --no-check-certificate "https://api.linode.com/?api_key=${KEY}&api_action=domain.resource.update&domainid=${DOMAINID}&resourceid=${RESOURCEIDAAAA}&target=[remote_addr]"
